<a href="https://colab.research.google.com/github/jotapesete7/Minhas-aulas/blob/main/primeiro_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np


In [16]:
matriz = np.random.rand(3,3)
print('Matriz original:')
print(matriz)


Matriz original:
[[0.36255751 0.55983361 0.36468958]
 [0.34486068 0.35243185 0.34134094]
 [0.23176685 0.64279566 0.13993284]]


In [18]:
matriz_transposta = np.transpose(matriz)
print('Matriz transposta:')
print(matriz_transposta)

Matriz transposta:
[[0.36255751 0.34486068 0.23176685]
 [0.55983361 0.35243185 0.64279566]
 [0.36468958 0.34134094 0.13993284]]
